#!/bin/sh -e

shake_options=${SHAKE_OPTIONS:--j}

which stack 1>/dev/null \
  || (echo "Please install stack from http://haskellstack.org" ; exit 1)

stack build --no-system-ghc --install-ghc
`stack path --local-install-root`/bin/shake-processing-sound $shake_options "$@"
